"""new fields in user model

Revision ID: 197b1785dc86
Revises: 4574164cdc09
Create Date: 2019-12-28 19:20:30.020034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197b1785dc86'
down_revision = '4574164cdc09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
