"""followers

Revision ID: 568a8820d87a
Revises: 197b1785dc86
Create Date: 2019-12-30 15:18:03.181669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568a8820d87a'
down_revision = '197b1785dc86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
